USE [master]
GO

/****** Object:  Database [InventoryManagement]    Script Date: 19-03-2022 17:05:45 ******/
CREATE DATABASE [InventoryManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'InventoryManagement', FILENAME = N'D:\MY STUDY\dotnet\InventoryManagement\DATABASE\InventoryManagement.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'InventoryManagement_log', FILENAME = N'D:\MY STUDY\dotnet\InventoryManagement\DATABASE\InventoryManagement_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [InventoryManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [InventoryManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [InventoryManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [InventoryManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [InventoryManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [InventoryManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [InventoryManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [InventoryManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [InventoryManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [InventoryManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [InventoryManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [InventoryManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [InventoryManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [InventoryManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [InventoryManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [InventoryManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [InventoryManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [InventoryManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [InventoryManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [InventoryManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [InventoryManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [InventoryManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [InventoryManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [InventoryManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [InventoryManagement] SET  MULTI_USER 
GO

ALTER DATABASE [InventoryManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [InventoryManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [InventoryManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [InventoryManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [InventoryManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [InventoryManagement] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [InventoryManagement] SET QUERY_STORE = OFF
GO

ALTER DATABASE [InventoryManagement] SET  READ_WRITE 
GO

